

# Font Options
# normal = { family = "<string>", stye = "<string>" }

[window]
opacity = 0.65
decorations_theme_variant = "Dark"


[font]
normal = { family = "Terminess Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { family = "Bold Italic" }
size = 12.5


[selection]
save_to_clipboard = true


[cursor]
style = { shape = "Beam", blinking = "On" }
blink_timeout = 0
unfocused_hollow = true


[mouse]
hide_when_typing = true







